## 应用程序配置
hp.soa.web:
  # Cookie 生命周期（默认：10年）
  cookie:
    max-age: 315360000
  # 跨域访问配置
  cors:
    mapping: "/**"
    allowed-origins: "*"
    allowed-headers: "*"
    allowed-methods: "*"
    exposed-headers: 
    allow-credentials: false
    max-age: 3600
  # 异步服务（io.github.hpsocket.soa.framework.web.service.AsyncService）配置
  async:
    enabled: true
    core-pool-size: 4
    max-pool-size: 16
    keep-alive-seconds: 30
    queue-capacity: 2000
    rejection-policy: CALLER_RUNS
    allow-core-thread-time-out: true