## 应用程序配置
hp.soa.web:
  # HTTP 配置
  http:
    # 日期时间序列化格式（默认："yyyy-MM-dd'T'HH:mm:ss.SSSXXX"）
    date-time-format: "yyyy-MM-dd HH:mm:ss.SSS"
    # 请求响应中是否返回请求 ID（默认：false）
    return-request-id: true
    cookie:
      # （默认值：10年）
      max-age: 315360000
      # （默认值：false）
      secure: false
      # （默认值：false）
      http-only: false
      # （可选值：Strict、Lax、None，默认值：Lax）
      same-site: Lax
    # 跨域访问配置
    cors:
      mapping: "/**"
      allowed-origins: "*"
      allowed-headers: "*"
      allowed-methods: "*"
      exposed-headers: 
      allow-credentials: false
      max-age: 3600
  # 异步服务（io.github.hpsocket.soa.framework.web.service.AsyncService）配置
  async:
    enabled: true
    core-pool-size: 4
    max-pool-size: 16
    keep-alive-seconds: 30
    queue-capacity: 2000
    # CALLER_RUNS, ABORT, DISCARD, DISCARD_OLDEST, SYNC
    rejection-policy: CALLER_RUNS
    allow-core-thread-time-out: true