hp.soa.gid.leaf:
  snowflake:
    #enable: true
    leaf-name: hp-soa
    zk-address: 192.168.56.23:2181
    server-port: ${server.port}
  segment:
    enable: true
    url: "jdbc:mysql://192.168.56.23:3306/leaf_db?serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true"
    username: leaf
    # encrypt password by druid public-key
    #password: "Vt4ZT5CSHb9wpO4b0fx7uSX8UxGkyTEc3ycZZhWZcz++Ehkg0Dtzhi7s2XB8fLFAcjgKilUv0iN5Fasb4dNQ1w=="
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 10
    min-idle: 1
    max-wait: 3000
    initial-size: 3
    keep-alive: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1
    validation-query-timeout: 1
    filters: stat,wall,slf4j
    #query-timeout: (seconds, 0: infinite)
    #transaction-query-timeout: (seconds, 0: infinite)
    default-transaction-isolation: 2
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
    # public-key uses to encrypt database access password
    #public-key: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJRhKGNr3IAJcs4+0ys/4zmwUJoBYqAdx6EcyiWIBt7cIFS5QdruakTmGk8XOVPMVz9jOLOvhPfjLzgPgwaKo6UCAwEAAQ=="