## Leaf 分布式全局ID生成器配置
hp.soa.gid.leaf:
  # 雪花ID生成器配置
  snowflake:
    # 是否开启（默认：true）
    #enabled: true
    # zk leaf 节点名称（默认：default）
    leaf-name: hp-soa
    zk-address: 192.168.56.23:2181
    # 服务端口（默认：${server.port}），用于生成 workerId
    server-port: ${server.port}
  # 段号ID生成器配置（配置方式参考 Druid 数据库连接池）
  segment:
    # 是否开启（默认：false）
    enabled: true
    # 数据源名称（默认：leaf）
    data-source: leaf

## Leaf 段号数据源
spring.datasource.dynamic.datasource:
  leaf:
    url: "jdbc:mysql://192.168.56.23:3306/leaf_db?serverTimezone=Asia/Shanghai&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&failOverReadOnly=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true"
    username: leaf
    # encrypt password by druid public-key
    #password: "Vt4ZT5CSHb9wpO4b0fx7uSX8UxGkyTEc3ycZZhWZcz++Ehkg0Dtzhi7s2XB8fLFAcjgKilUv0iN5Fasb4dNQ1w=="
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
