## 默认 RabbitMQ 配置
spring.rabbitmq:
  addresses: 192.168.56.23:5672
  username: rabbit
  password: 123456
  virtual-host: "/"
  publisher-confirm-type: correlated
  publisher-returns: true
  listener:
    simple:
      missing-queues-fatal: false
    direct:
      missing-queues-fatal: false
    stream:
      native-listener: true
  template:
    mandatory: true
  stream:
    host: 192.168.56.23
    port: 5552
    name: default-stream

## （默认 RabbitMQ 之外）第一个RabbitMQ 配置
spring.rabbitmq-first:
  addresses: 192.168.56.23:5672
  username: rabbit
  password: 123456
  virtual-host: "first"
  publisher-confirm-type: correlated
  publisher-returns: true
  listener:
    simple:
      missing-queues-fatal: false
    direct:
      missing-queues-fatal: false
    stream:
      native-listener: true
  template:
    mandatory: true
  stream:
    host: 192.168.56.23
    port: 5552
    name: first-stream

## （默认 RabbitMQ 之外）第二个RabbitMQ 配置
spring.rabbitmq-second:
  addresses: 192.168.56.23:5672
  username: rabbit
  password: 123456
  virtual-host: "second"
  publisher-confirm-type: correlated
  publisher-returns: true
  listener:
    # stream listener
    type: stream
    simple:
      missing-queues-fatal: false
    direct:
      missing-queues-fatal: false
    stream:
      # native listener
      native-listener: true
  template:
    mandatory: true
  stream:
    host: 192.168.56.23
    port: 5552
    name: second-stream

## （默认 RabbitMQ 之外）第三个RabbitMQ 配置
spring.rabbitmq-third:
  addresses: 192.168.56.23:5672
  username: rabbit
  password: 123456
  virtual-host: "third"
  publisher-confirm-type: correlated
  publisher-returns: true
  listener:
    # stream listener
    type: stream
    simple:
      missing-queues-fatal: false
    direct:
      missing-queues-fatal: false
    stream:
      # no-native listener
      native-listener: false
  template:
    mandatory: true
  stream:
    host: 192.168.56.23
    port: 5552
    name: third-stream
