seata:
  enabled: true
  application-id: ${spring.application.name}  
  # 事务群组（可以每个应用独立取名，也可以使用相同的名字）
  tx-service-group: default_tx_group
  # 当 seata.config.type=nacos 时，以下 client 配置有效
  client:
    rm:
      report-success-enable: true
      # 自动刷新缓存中的表结构（默认false）
      table-meta-check-enable: false
      # 一阶段结果上报TC重试次数（默认5）
      report-retry-count: 5
      # 异步提交缓存队列长度（默认10000）
      async-commit-buffer-limit: 10000
      lock:
          # 校验或占用全局锁重试间隔（默认10ms）
          retry-internal: 1
          # 校验或占用全局锁重试次数（默认30）
          retry-times: 30
          # 分支事务与其它全局回滚事务冲突时锁策略（优先释放本地锁让回滚成功）
          retry-policy-branch-rollback-on-conflict: true
    tm:
      # 一阶段全局提交结果上报TC重试次数（默认1次，建议大于1）
      commit-retry-count: 3
      # 一阶段全局回滚结果上报TC重试次数（默认1次，建议大于1）
      rollback-retry-count: 3
      # 默认全局事务超时时间（毫秒，默认：60000）
      default-global-transaction-timeout: 30000
    undo:
      # 二阶段回滚镜像校验（默认true开启）
      data-validation: true
      # undo序列化方式（默认jackson）
      log-serialization: fastjson 
      # 自定义undo表名（默认undo_log）
      log-table: undo_log
    log:
      # 日志异常输出概率（默认100）
      exceptionRate: 100
    support:
      spring:
        datasource-autoproxy: true
  # 当 seata.registry.type=nacos 时，以下 service 配置有效
  service:
    #vgroupMapping:
    vgroup-mapping:
      # TC 集群（必须与seata-server保持一致）
      default_tx_group: default
    # 降级开关
    enable-degrade: false
    # 禁用全局事务（默认false）
    disable-global-transaction: false
    grouplist:
      default: 192.168.56.23:8091
    #default:
    #  grouplist: 192.168.56.23:8091
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    # 客户端事务消息请求是否批量合并发送（默认true）
    enable-client-batch-send-request: true
  registry:
    type: file
    file:
      name: file.conf
    nacos:
      # 默认：seata-server，Server和Client端的值需一致
      application: seata-server
      server-addr: 192.168.56.23:8848
      namespace: DEV
      cluster: default
      group: SEATA_GROUP
      username: nacos
      password: 123456
  config:
    type: file
    file:
      name: file.conf
    nacos:
      server-addr: 192.168.56.23:8848
      namespace: DEV
      group: GLOBAL_GROUP
      username: nacos
      password: 123456
      data-id: seata.yml

# 当 seata.registry.type=file 时，以下配置有效
service:
  vgroupMapping:
  #vgroup-mapping:
    # TC 集群（必须与seata-server保持一致）
    default_tx_group: default
  # 降级开关
  enable-degrade: false
  # 禁用全局事务（默认false）
  disable-global-transaction: false
  #grouplist:
  #  default: 192.168.56.23:8091
  default:
    grouplist: 192.168.56.23:8091
