## Sentinel 流控配置
spring.cloud.sentinel:
  # 是否开启
  enabled: true
  # 是否立即加载
  eager: true
  filter:
    enabled: true
  log:
    dir: /data/logs/sentinel
    switch-pid: true
  transport:
    # 上报 Dashboard 地址
    dashboard: 192.168.56.23:8383
    heartbeat-interval-ms: 30000
  # 流控规则数据源
  datasource:
    # 流控规则
    flow:
      nacos:
        server-addr: 192.168.56.23:8848
        username: nacos
        password: 123456
        namespace: DEV
        groupId: SENTINEL_GROUP
        dataId: ${spring.application.name}-flow-rules
        data-type: json
        rule-type: flow
    # 熔断规则
    degrade:
      nacos:
        server-addr: 192.168.56.23:8848
        username: nacos
        password: 123456
        namespace: DEV
        groupId: SENTINEL_GROUP
        dataId: ${spring.application.name}-degrade-rules
        data-type: json
        rule-type: degrade
    # 热点规则
    param-flow:
      nacos:
        server-addr: 192.168.56.23:8848
        username: nacos
        password: 123456
        namespace: DEV
        groupId: SENTINEL_GROUP
        dataId: ${spring.application.name}-param-rules
        data-type: json
        rule-type: param-flow
    # 系统规则
    system:
      nacos:
        server-addr: 192.168.56.23:8848
        username: nacos
        password: 123456
        namespace: DEV
        groupId: SENTINEL_GROUP
        dataId: ${spring.application.name}-system-rules
        data-type: json
        rule-type: system
    # 授权规则
    authority:
      nacos:
        server-addr: 192.168.56.23:8848
        username: nacos
        password: 123456
        namespace: DEV
        groupId: SENTINEL_GROUP
        dataId: ${spring.application.name}-authority-rules
        data-type: json
        rule-type: authority
    #gw-flow:
    #  nacos:
    #    server-addr: 192.168.56.23:8848
    #    username: nacos
    #    password: 123456
    #    namespace: DEV
    #    groupId: SENTINEL_GROUP
    #    dataId: ${spring.application.name}-gw-flow-rules
    #    data-type: json
    #    rule-type: gw-flow
    #gw-api-group:
    #  nacos:
    #    server-addr: 192.168.56.23:8848
    #    username: nacos
    #    password: 123456
    #    namespace: DEV
    #    groupId: SENTINEL_GROUP
    #    dataId: ${spring.application.name}-gw-api-group-rules
    #    data-type: json
    #    rule-type: gw-api-group
