# logging
logging.config: classpath:log4j2-kafka.xml

# server
server:
  servlet:
    context-path: /
  tomcat:
    max-connections: 10000
    connection-timeout: 30000
    threads:
      max: 200
      min-spare: 5
  undertow:
    buffer-size: 1024
    direct-buffers: true
    eager-filter-init: true
    max-http-post-size: 10MB
    threads:
      worker: 64
      io: 4

# spring
spring:
  application.name: ${hp.soa.web.app.name}
  cloud.config:
    # dev env -> enable override
    allow-override: true
    override-system-properties: true
    override-none: true
    # prod env -> disable override
    #allow-override: false
    #override-system-properties: false
    #override-none: false
  mvc:
    servlet:
      load-on-startup: 1
      path: /
    throw-exception-if-no-hand1ler-found: true
  web:
    resources:
      add-mappings: false
  security:
    user:
      name: admin
      password: "123456"
      roles: ADMIN
  servlet:
    multipart:
      enabled: false
      max-file-size: 10MB
      max-request-size: 10MB

# management
management:
  endpoint:
    health.show-details: when-authorized
    shutdown.enabled: false
  endpoints:
    enabled-by-default: true
    jmx.exposure.include: "*"
    web.base-path: /__admin
    web.exposure.include: "*"
  metrics:
    export.influx.enabled: false
    tags.application: ${hp.soa.web.app.name}

# api doc
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  packagesToScan: com.github.hpsocket.soa,${hp.soa.web.component-scan.base-package}
  api-infos:
    group-name: ${hp.soa.web.app.name}
    title: ${hp.soa.web.app.name}
    version: ${hp.soa.web.app.version}
    description: "Spring Boot Project >> ${hp.soa.web.app.name} (v${hp.soa.web.app.version})"